FROM node:18-slim

WORKDIR /app

RUN apt-get update \
 && apt-get install -y openssl \
 && rm -rf /var/lib/apt/lists/*


COPY package.json package-lock.json* ./
RUN npm install

COPY . .

CMD ["node", "src/worker.js"]
